routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function (){
   return view('home');
});


Route::group(['middleware'=>'auth', 'namespace'=>'Admin', 'as'=>'admin.', 'prefix'=>'admin'], function (){

    Route::get('/dashboard', [
        'as' => 'dashboard',
        'uses' => 'Dashboard@index',
    ]);

    Route::resource('/careers', 'CareersController');
    Route::resource('/locations', 'LocationController');
    Route::resource('/mng_srvc', 'ManagementServicesController');
    Route::resource('locations', 'LocationController');
});


Auth::routes();

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $fillable = [ 'name', 'address', 'description', 'area', 'bedrooms', 'bathrooms', 'link', 'latitude', 'longitude', 'image'];
}

app/Http/Controllers/Admin/LocationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Location;
use Illuminate\Http\Request;

class LocationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $locations = Location::all();
        return view('locations.index', compact('locations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('locations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //  $flight = new Flight;
        //  $flight->name = $request->name;
        //  $flight->save();
        $input = $request->all();
        Location::create($input);
        return redirect('admin/locations');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function show(Location $location)
    {
        //  $locationRec = Location::findorFail($location);
        return view('locations.show', compact('location'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function edit(Location $location)
    {
        return view('locations.edit', compact('location'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Location $location)
    {
        // $locationRec = Location::findOrFail($location);
        $input = $request->all();
        $location->update($input);
        return redirect('admin/locations');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Location  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $locationRec = Location::findOrFail($id);
        $locationRec->delete();

        return redirect('admin/locations');
    }
}

resources/views/locations/create.blade.php
@extends('layouts.app')
@section('content')
    <div class='col-md-6 col-md-offset-3'>
        <h1>Add New Candidate</h1>
        <hr>

        {!! Form::open(['action' => 'Admin\LocationController@store', 'id' => 'community_location', 'files' => true]) !!}
        @include('locations.form', ['submitButtonText' => 'Add Candidate'])
        {!! Form::close() !!}
    </div>
@stop

resources/views/locations/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class='col-md-6 col-md-offset-3'>
        <h1>Edit Candidate</h1>
        <hr>

        {!! Form::model($location, ['method' => 'PATCH', 'action' => ['Admin\LocationController@update',$location->id]]) !!}
        @include('locations.form', ['submitButtonText' => 'Edit Candidate'])
        {!! Form::close() !!}
    </div>
@stop

resources/views/locations/form.blade.php
<div class='form-group'>
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('address', 'Address:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('latitude', 'Latitude:') !!}
    {!! Form::text('latitude', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('longitude', 'Longitude:') !!}
    {!! Form::text('longitude', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('area', 'Area (Sq ft):') !!}
    {!! Form::text('area', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('bedrooms', 'Bedrooms:') !!}
    {!! Form::text('bedrooms', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('bathrooms', 'Bathrooms:') !!}
    {!! Form::text('bathrooms', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('link', 'Link:') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image', ['class' => 'form-control']) !!}
</div>
<div class='form-group'>
    {!! Form::submit($submitButtonText, ['class' => 'btn btn-lg btn-success form-control']) !!}
</div>

resources/views/locations/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Area sq ft</th>
                            <th scope="col">No of beds</th>
                            <th scope="col">No of baths</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($locations as $location)
                            <tr>
                                <th scope="row">
                                    <a href="{{ url('/admin/locations', $location->id) }}">
                                        {{ $location->name }}
                                    </a>
                                </th>
                                <td>{{ $location->area }}</td>
                                <td>{{ $location->beds }}</td>
                                <td>{{ $location->baths }}</td>
                                <td>
                                    <a href="{{ route('admin.locations.edit', $location->id) }}">
                                        Edit Location
                                    </a>
                                    <form action="/task/{{ $task->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}

                                        <button>Delete Task</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                                <p>There are no location to display!</p>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/locations/show.blade.php
@extends('layouts.app')
@section('content')
    <h1>{{ $location->name }}</h1>
    <div class='body'>
        <pre>{{ $location }}</pre>
    </div>
@stop